services:
  td-spring:
    image: td-spring:6
    container_name: td-spring-app-compose
    build:
      context: .
    ports:
      - "8080:8080"
      - "8090:8080"
    networks:
      - td-network
#    environment:
#      DB_HOST: db
#      DB_NAME: student_db
#      DB_USER: postgres
#      DB_PASS: 123456Aa

  db:
    image: postgres
    networks:
      - td-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql

  prometheus:
    image: prom/prometheus:v2.35.0
    #network_mode: host
    networks:
      - td-network
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    #network_mode: host
    networks:
      - td-network
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000 # access grafana url
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

networks:
  td-network:
