spring:
  application:
    name: texnoera
  messages:
    encoding: UTF-8
    basename: i18n/messages
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 60000
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: "all"
      batch-size: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: "lz4"
      retries: 0
      client-id: texnoera
      properties:
        spring.json.type.mapping: "UserCreatedEvent:com.texnoera.messaging.event.UserCreatedEvent"
  jpa:
    show-sql: true
    open-in-view: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

server:
  port: 8081

application:
  whitelist:
    user: 9

logging:
  level:
    root: info
    com.texnoera: debug

springdoc:
  api-docs:
    path: /v3/api-docs

cache:
  redis:
    user:
      ttl: 10 #seconds

kafka:
  topics:
    user_creation:
      name: user_creation
      partitions: 3
      replicas: 1
      min-in-sync-replicas: 1

client:
  card:
    url: http://localhost:8080